# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "ray-tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.15.0"
rand = "0.8.5"
